### ISSUE TITLE
Servers that drop out of sync are assigned default Hostgroup when coming back in sync

### ISSUE THREAD

**Issue by iwalmsley** [theforeman/foreman_default_hostgroup#26]
As described, if a server drops out of sync by over one week (or however long reports are kept for), when it comes back in sync (can happen for various reasons), it is assigned the default host group as if it were a new server.

**Comment by GregSutcliffe** [comment]
Thanks for the bug report! That's interesting, because according to https://github.com/theforeman/foreman_default_hostgroup/blob/develop/lib/default_hostgroup_base_host_patch.rb#L65 the host needs to be no older than 300s to pass that check.

Also, presumably these out of sync hosts have no hostgroup set? Or are you using `force_hostgroup_match = true`?

**Comment by UnicodeTreason** [comment]
I've completed some testing, and in reconnecting an out of sync host (3 months out of sync) I had no issues with it getting a host group incorrectly.

## Details:
### Plugin Settings
> force_host_environment | Yes | 
force_hostgroup_match | No | 
force_hostgroup_match_only_new | Yes |

### Host
Had no host group when out of sync, still has no host group after coming back in sync.

**Comment by GregSutcliffe** [comment]
That would be expected then, since with "only_new" set, it looks at the creation time of the Host object in the db - if that's older than 300s then it doesn't touch anything.

I guess we can close this then, since there's been no further reply from @iwalmsley - do re-open if it's still an issue for you!
